version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: healthycarbs-postgres
    restart: always
    environment:
      POSTGRES_DB: healthy_carbs
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # mongodb:
  #   image: mongo:7
  #   container_name: healthycarbs-mongodb
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongoadmin
  #     MONGO_INITDB_ROOT_PASSWORD: mongopass
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodata:/data/db

  backend:
    container_name: healthycarbs-backend
    build: ./backend
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"

  frontend:
    container_name: healthycarbs-frontend
    build: ./frontend
    ports:
      - "4200:80"

volumes:
  pgdata:
  mongodata: